# HTTP Server
server:
  address: :80

# shimo auth information
shimoauth:
  clientId: kDQJ6vWgWWwq8r8H
  clientSecret: kDQJ6vWgWWwq8r8H
  username: kDQJ6vWgWWwq8r8H@gmail.com
  password: kDQJ6vWgWWwq8r8H
  scope: read

dbinfo:
  dbname: "whsupport"
  addr: "127.0.0.1:3306"
  user: "root"
  pwd: "123456"

uploadPath: "./upload"