# HTTP Server
server:
  address: :80

# EDIT ME: Shimo Cookie (get from https://shimo.im/ )
cookie: foo=bar

# Shimo Document ID
documents:
  accommodations: 6c6GKvX83hRCVdG8
  platforms: kDQJ6vWgWWwq8r8H

# shimo auth information
shimoauth:
  clientId: kDQJ6vWgWWwq8r8H
  clientSecret: kDQJ6vWgWWwq8r8H
  username: kDQJ6vWgWWwq8r8H@gmail.com
  password: kDQJ6vWgWWwq8r8H
  scope: read
